#ifndef PIX2ASCII_ERROR_H
#define PIX2ASCII_ERROR_H

enum error {
    SUCCESS,
    FOPEN_ERROR,
    POPEN_ERROR,
    ARG_COUNT_ERROR,
    FLAG_ERROR,
    FILE_PATH_ERROR,
    TERMINAL_COLORS_ERROR,
    COLOR_CHANGING_ERROR,
};

#endif //PIX2ASCII_ERROR_H
