#ifndef PIX2ASCII_ERROR_H
#define PIX2ASCII_ERROR_H

typedef enum {
    SUCCESS,
    HELP_FLAG,
    NOT_IMPLEMENTED_ERROR,
    ARG_COUNT_ERROR,
    FLAG_ERROR,
    RESOLUTION_OBTAINING_ERROR,
    FOPEN_ERROR,
    POPEN_ERROR,
    FRAME_ALLOCATION_ERROR,
    TERMINAL_COLORS_ERROR,
    KERNEL_UPDATE_ERROR
} return_code_t;

#endif //PIX2ASCII_ERROR_H
